name: Update ORCID Publications

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-publications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull ORCID Data
        uses: svay/orcid-profile@main
        with:
          orcid-id: '0009-0000-1697-1424' # 🚨 Replace with your ID (e.g., 0000-0002-XXXX-XXXX)
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update publications from ORCID" || exit 0
          git push
